"""Provider-neutral application contracts for bounded review work."""

from .discovery import (
    AssetDescriptor,
    AssetMediaType,
    DiscoveryCheckpoint,
    DiscoveryPage,
    DiscoveryProgress,
)
from .integration import (
    AssetContentPort,
    AssetDiscoveryPort,
    CapabilityPort,
    DiscoveryDispatcher,
    IntegrationCapabilities,
    ReviewSynchronizationPort,
    WorkRequest,
    WorkSink,
    WorkSource,
)
from .state import (
    AnalysisRevision,
    DiscoveryCommitOutcome,
    DiscoveryCommitResult,
    DiscoveryResumeState,
    DurableDiscoveryCoordinator,
    DurableWorkSink,
    EnqueueOutcome,
    EnqueueResult,
    FailureDisposition,
    ProcessingFailure,
    ProcessingKey,
    ProcessingStatePort,
    ProcessingStatus,
    StateConflictError,
    StateStoreError,
    WorkClaim,
)

__all__ = [
    "AssetContentPort",
    "AssetDescriptor",
    "AssetDiscoveryPort",
    "AssetMediaType",
    "CapabilityPort",
    "DiscoveryDispatcher",
    "DiscoveryCheckpoint",
    "DiscoveryPage",
    "DiscoveryProgress",
    "IntegrationCapabilities",
    "ReviewSynchronizationPort",
    "WorkRequest",
    "WorkSink",
    "WorkSource",
    "AnalysisRevision",
    "DiscoveryCommitOutcome",
    "DiscoveryCommitResult",
    "DiscoveryResumeState",
    "DurableDiscoveryCoordinator",
    "DurableWorkSink",
    "EnqueueOutcome",
    "EnqueueResult",
    "FailureDisposition",
    "ProcessingFailure",
    "ProcessingKey",
    "ProcessingStatePort",
    "ProcessingStatus",
    "StateConflictError",
    "StateStoreError",
    "WorkClaim",
]
